// FILE: Models.swift

import Foundation
import CoreLocation

// MARK: - User Profile Model (From your Mock Data)
// This model represents the raw data structure from your backend or mock service.

//struct UserProfile: Identifiable {
//    let id: String // Corresponds to userId
//    let displayName: String
//    let description: String
//    let skills: [String]
//    let interests: [String]
//    let friends: [String]
//    let friendRequests: [String]
//
//    init?(userId: String, data: [String: Any]) {
//        guard
//            let displayName = data["displayName"] as? String,
//            let description = data["description"] as? String,
//            let skills = data["skills"] as? [String],
//            let interests = data["interests"] as? [String],
//            let friends = data["friends"] as? [String],
//            let friendRequests = data["friendRequests"] as? [String]
//        else {
//            return nil
//        }
//        self.id = userId
//        self.displayName = displayName
//        self.description = description
//        self.skills = skills
//        self.interests = interests
//        self.friends = friends
//        self.friendRequests = friendRequests
//    }
//}


// MARK: - Recommendation System Model (Used by the AI Engine)

/// This is the primary model used by the RecommendationEngine and MapView.
/// It includes a full custom Codable implementation to handle the non-standard `CLLocationCoordinate2D`.
struct User: Identifiable, Codable {
    let id: UUID
    let userId: String
    var name: String
    var bio: String
    var interests: [String]
    var skills: [String]
    var projectIdeas: [String]
    var profileImage: String?
    var coordinate: CLLocationCoordinate2D

    /// Custom Coding Keys are defined to handle properties that are not directly Codable.
    /// We break `coordinate` down into `latitude` and `longitude` for serialization.
    enum CodingKeys: String, CodingKey {
        case id, userId, name, bio, interests, skills, projectIdeas, profileImage
        case latitude
        case longitude
    }

    // MARK: - Encoder
    
    /// Encodes this `User` object into a format like JSON.
    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        
        try container.encode(id, forKey: .id)
        try container.encode(userId, forKey: .userId)
        try container.encode(name, forKey: .name)
        try container.encode(bio, forKey: .bio)
        try container.encode(interests, forKey: .interests)
        try container.encode(skills, forKey: .skills)
        try container.encode(projectIdeas, forKey: .projectIdeas)
        try container.encodeIfPresent(profileImage, forKey: .profileImage)
        
        // Encode the coordinate by breaking it into two separate Double values.
        try container.encode(coordinate.latitude, forKey: .latitude)
        try container.encode(coordinate.longitude, forKey: .longitude)
    }

    // MARK: - Decoder

    /// Creates a new `User` instance by decoding from a format like JSON.
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        
        id = try container.decode(UUID.self, forKey: .id)
        userId = try container.decode(String.self, forKey: .userId)
        name = try container.decode(String.self, forKey: .name)
        bio = try container.decode(String.self, forKey: .bio)
        interests = try container.decode([String].self, forKey: .interests)
        skills = try container.decode([String].self, forKey: .skills)
        projectIdeas = try container.decode([String].self, forKey: .projectIdeas)
        profileImage = try container.decodeIfPresent(String.self, forKey: .profileImage)
        
        // Decode latitude and longitude, then re-assemble them into a CLLocationCoordinate2D.
        let latitude = try container.decode(CLLocationDegrees.self, forKey: .latitude)
        let longitude = try container.decode(CLLocationDegrees.self, forKey: .longitude)
        coordinate = CLLocationCoordinate2D(latitude: latitude, longitude: longitude)
    }
    
    // MARK: - Memberwise Initializer
    
    /// Because we provided a custom `init(from decoder:)`, the automatic memberwise initializer
    /// is no longer generated by Swift. We must re-define it here so we can still create
    /// `User` instances manually in our code (e.g., in the DataMapper).
    init(id: UUID = UUID(), userId: String, name: String, bio: String, interests: [String], skills: [String], projectIdeas: [String], profileImage: String? = nil, coordinate: CLLocationCoordinate2D) {
        self.id = id
        self.userId = userId
        self.name = name
        self.bio = bio
        self.interests = interests
        self.skills = skills
        self.projectIdeas = projectIdeas
        self.profileImage = profileImage
        self.coordinate = coordinate
    }
}


// MARK: - Supporting Models

// These models do not require a custom Codable implementation.
// Swift can automatically synthesize their Codable conformance.

struct UserMatch: Identifiable {
    let id = UUID()
    let user: User
    let score: Double
    let matchDetails: MatchDetails
}

struct MatchDetails {
    let commonInterests: [String]
    let commonSkills: [String]
    let commonProjectThemes: [String]
    let interestScore: Double
    let skillScore: Double
    let projectScore: Double
}
